name: Push to next/kelvin/*

on:
  push:
    branches:
      - 'next/kelvin/*'
    paths:
      - 'build.zig'
      - 'build.zig.zon'
      - 'ext/**'
      - '!ext/**.md'
      - 'pkg/**'
      - '.github/workflows/**.yml'
      - '*.sh'

jobs:
  urbit:
    uses: ./.github/workflows/shared.yml
    with:
      upload: true
      next: ${{ github.ref_name }}
    secrets: inherit
