name: pre-release

on:
  release: null
  push:
    branches:
      - release

jobs:
  call-vere:
    uses: ./.github/workflows/shared.yml
    with:
      pace: 'soon'
      upload: true
    secrets: inherit
