name: Push to release

on:
  push:
    branches:
      - release
    paths:
      - 'build.zig'
      - 'build.zig.zon'
      - 'ext/**'
      - '!ext/**.md'
      - 'pkg/**'
      - '.github/workflows/**.yml'
      - '*.sh'

jobs:
  urbit:
    uses: ./.github/workflows/shared.yml
    with:
      pace: 'soon'
      upload: true
    secrets: inherit

  docker:
    uses: ./.github/workflows/docker-shared.yml
    with:
      pace: 'soon'
    secrets: inherit
