name: release

on:
  release: null
  push:
    branches:
      - master

jobs:
  call-vere:
    uses: ./.github/workflows/shared.yml
    with:
      docker: true
      pace: 'live'
      upload: true
    secrets: inherit
